apiVersion: v1
kind: Service
metadata:
  name: newsfeed-app-service
  labels:
    app: newsfeed-app
spec:
  type: NodePort
  selector:
    app: newsfeed-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
      protocol: TCP
      name: http
